### ISSUE TITLE
use purrr

### ISSUE THREAD

**Issue by ijlyttle** [uncoast-unconf/steward#71]
Here is my confession and my apology to my uncoast-unconf collaborators: @nikdata, @stephaniereinders, @AmandaRaeISU, and @Ranae.

When we began the development of this package at the unconf in Des Moines, I suggested (insisted might be a better word) that we not depend on purrr, and that we use base equivalents instead.

**I made the wrong decision.**

As I have been developing this package, I have been writing evermore contorted code that would be cleaner and, frankly, better using purrr. Then today, I noticed (and I should have checked when we began) that usethis, which we import, itself imports purrr, so we would not be adding to the dependencies of this package if we were to import purrr.

As such, I propose to import purrr, and as penance over the next little while, I will convert bits of code to their cleaner purrr equivalents.

![sorry](https://media.giphy.com/media/13IZ4VBHezN0k0/giphy.gif)

**Comment by AmandaRaeISU** [comment]
Ha! what a great issue/apology to receive. I have been going through UU withdrawals for the past month now. Thank you for you continuous work on steward Ian! I concur on purrr.

**Comment by Ranae** [comment]
I admire your willingness to try and do everything the right way, even when it is not obvious what the right way is! Welcome, purrr!
